//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.06.27 at 12:18:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://it.camp.pl/countries/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pl.camp.it.countries;
